/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.awt.image.BufferedImage;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
class AppTest {

    @Autowired
    private GraphicsLoader loadGraphics;

    @Test
    void testLoadAndRotate() {
        assertNotNull(loadGraphics, "GraphicsLoader should be autowired");
        Map<String, BufferedImage> images = loadGraphics.getImages();
        assertFalse(images.isEmpty(), "Images should be loaded");
        
        BufferedImage img = images.get("battleship.psd");
        assertNotNull(img, "battleship.psd should be loaded");
        
        BufferedImage rotated = loadGraphics.rotate(img, 90);
        assertNotNull(rotated, "Rotated image should not be null");
        
        // Now rotated image should always be SPRITE_SIZE x SPRITE_SIZE
        assertEquals(Constants.SPRITE_SIZE, rotated.getWidth(), "Width of rotated image should be SPRITE_SIZE");
        assertEquals(Constants.SPRITE_SIZE, rotated.getHeight(), "Height of rotated image should be SPRITE_SIZE");
        
        BufferedImage copy = loadGraphics.copy(img);
        assertNotNull(copy, "Copy should not be null");
        assertEquals(img.getWidth(), copy.getWidth());
        assertEquals(img.getHeight(), copy.getHeight());
        assertNotSame(img, copy, "Copy should be a different object");

        BufferedImage resized = loadGraphics.resize(img, Constants.SPRITE_SIZE, Constants.SPRITE_SIZE);
        assertEquals(Constants.SPRITE_SIZE, resized.getWidth());
        assertEquals(Constants.SPRITE_SIZE, resized.getHeight());

        BufferedImage sheet = loadGraphics.generateSpriteSheet(img);
        assertNotNull(sheet, "Sprite sheet should not be null");
        assertEquals(Constants.SPRITE_SIZE * 32, sheet.getWidth(), "Sheet width should be 16 * 32");
        assertEquals(Constants.SPRITE_SIZE, sheet.getHeight(), "Sheet height should be 16");

        // Verify pre-generated rotations
        java.util.List<BufferedImage> rotations = loadGraphics.getRotatedImages().get("battleship.psd");
        assertNotNull(rotations, "Rotations for battleship.psd should be pre-generated");
        assertEquals(32, rotations.size(), "Should have 32 rotations");
        for (BufferedImage rotation : rotations) {
            assertEquals(Constants.SPRITE_SIZE, rotation.getWidth());
            assertEquals(Constants.SPRITE_SIZE, rotation.getHeight());
        }

        // Verify combined sprite sheet
        BufferedImage combined = loadGraphics.generateCombinedSpriteSheet();
        assertNotNull(combined, "Combined sheet should not be null");
        int numUnits = loadGraphics.getRotatedImages().size();
        assertEquals(Constants.SPRITE_SIZE * 32, combined.getWidth(), "Combined width should be 32 * SPRITE_SIZE");
        assertEquals(Constants.SPRITE_SIZE * numUnits, combined.getHeight(), "Combined height should be numUnits * SPRITE_SIZE");
    }
}
